Iter15
kommunist/mishin-shortener pull request #20
Opened 2024-08-24 07:25 UTC by kommunist

2024-09-03 00:13 UTC, vokinneberg requested changes
Поздравляю с первым ревью четвёртого спринта! 🎉 В этом спринте мы коснулись, наверное, самых сложных тем: многопоточности и криптографии. Хочу сделать несколько предложений по улучшению и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Код функционален, корректен и проходит тесты! 🚀
2. Ты лаконично встроил изменения в структуру существующего приложения. 👍
3. Ты покрыл тестами новые компоненты и доработал существующие тесты после изменения. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Мне кажется, что реализация использованием воркера и паттерна `fanIn` могла бы выглядеть примерно таким образом:
    - При старте приложения мы запускаем горутину (воркер) в методе `mail`, которая читает из канала (буфера), когда он наполняется, и для всех задач на выполнение из буфера формирует батч, который выполняет, обновляя URLs. Потом приостанавливает работу, пока буфер опять не наполнится.
    - Хендлер, получив запрос на удаление, отправляет задачи на удаление в канал, из которого читает наша горутина, и сразу (не дожидаясь выполнения) возвращает ответ пользователю.
2. Было бы здорово реализовать обратную совместимость в других хранилищах.
3. Было бы здорово реализовать тесты для негативных кейсов.

2024-09-03 00:13 UTC, vokinneberg commented on cmd/shortener/main.go
> +	r.With(middleware.AuthCheck).Delete("/api/user/urls", h.DeleteURLs)
Можно сгруппировать маршруты:
```suggestion
r.Route("/api", func(r chi.Router) {
    r.Route("/shorten", func(r chi.Router) {
        r.With(middleware.AuthSet).Post("/", h.CreateURLByJSON)
        r.Post("/batch", h.CreateURLByJSONBatch)
    })
    r.Route("/user", func(r chi.Router) {
        r.With(middleware.AuthCheck).Get("/urls", h.UserURLs)
        r.Delete("/urls", h.DeleteURLs)
    })
})

```

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/filestorage/access.go
> +	return nil, nil
Было бы здорово реализовать обратную совместимость так же и для file storage.

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/handlers/create_url.go
> +		userID = ""
Мне кажется, что логичней было бы возвращать ошибку в случае отсутствия UserID. В противном случае хэндлеры будут работать неконсистентно.

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/handlers/deleteurls.go
> +	userID := u.(string)
Нужно ли здесь проверять, что userID отсутствует?

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/handlers/deleteurls_test.go
> +func TestDeleteURLs(t *testing.T) {
Было бы здорово проверить негативные кейсы.

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/handlers/userurls.go
> +	}
Мне кажется при такой записи возникает меньше когнитивной нагрузки.

```suggestion
	if len(data) == 0 {
	        w.WriteHeader(http.StatusNoContent)
	        return
	}
	
        for k, v := range data {
	        result = append(
		        result,
		        UserURLsItem{Short: h.Options.BaseRedirectURL + "/" + k, Original: v},
	        )
        }
        
        w.Header().Set("Content-Type", "application/json")
        w.WriteHeader(http.StatusOK)
        
        out, err := json.Marshal(result)
        if err != nil {
	        http.Error(w, "Error when create json", http.StatusInternalServerError)
	        return
        }
        
        w.Write(out)
```

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/mapstorage/storage.go
> +func (db *Storage) GetByUserID(ctx context.Context, userID string) (map[string]string, error) {
То же самое, было  бы здорово реализовать обратную совместимость.

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/pgstorage/access.go
> +	for _, v := range shorts {
Здесь лучше использовать либо batch update, либо transaction scope, так как если ошибка произойдет при апдейте одной из записей данные могут стать неконсистентными.

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/pgstorage/pgstorage.go
> +		`
Я бы рекомендовал не менять существующий скрипт, так как БД может быть уже создана в момент модификации, а либо выполнять дополнительную команду на добавление колонки, либо использовать миграции.

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/secure/secure_test.go
> +		original := "Lenin is a live!"
🫡

2024-09-03 00:13 UTC, vokinneberg commented on internal/app/handlers/deleteurls.go
> +	err = h.DB.DeleteByUserID(r.Context(), userID, list)
Мне кажется, что реализация  использованием воркера и паттерна `fanIn` могла бы выглядеть примерно таким образом:

- При старте приложения мы запускаем горутину (воркер) в методе `mail`, которая читает из канала (буфера), когда он наполняется, и для всех задач на выполнение из буфера формирует батч, который выполняет, обновляя URLs. Потом приостанавливает работу, пока буфер опять не наполнится.
- Хендлер, получив запрос на удаление, отправляет задачи на удаление в канал, из которого читает наша горутина, и сразу (не дожидаясь выполнения) возвращает ответ пользователю.

2024-09-04 08:40 UTC, kommunist commented on internal/app/handlers/deleteurls.go
> +	err = h.DB.DeleteByUserID(r.Context(), userID, list)
Понял.
Вытащил реализацию в отдельный пакет delasync и как хватило фантазии написал тест

2024-09-04 08:41 UTC, kommunist commented on internal/app/secure/secure_test.go
> +		original := "Lenin is a live!"
=)

2024-09-04 08:46 UTC, kommunist commented on internal/app/pgstorage/pgstorage.go
> +		`
Согласен.
Пока просто не стал заморачиваться, но в курсовой проект уже затащил миграции goose

2024-09-04 08:47 UTC, kommunist commented on internal/app/pgstorage/access.go
> +	for _, v := range shorts {
Затащил транзакцию

2024-09-04 08:47 UTC, kommunist commented on internal/app/handlers/deleteurls_test.go
> +func TestDeleteURLs(t *testing.T) {
Сделал тест на негативный сценарий, когда нет пользовтеля

2024-09-04 08:47 UTC, kommunist commented on internal/app/handlers/deleteurls.go
> +	userID := u.(string)
Проверка есть. Но добавил ошибку, если идет не так

2024-09-04 08:47 UTC, kommunist commented on internal/app/handlers/create_url.go
> +		userID = ""
Добавил ошибку

2024-09-04 08:48 UTC, kommunist commented on cmd/shortener/main.go
> +	r.With(middleware.AuthCheck).Delete("/api/user/urls", h.DeleteURLs)
Сгруппировал с учетом мидлварей

2024-09-04 08:48 UTC, kommunist commented on internal/app/handlers/userurls.go
> +	}
Да, поправил

2024-09-04 08:49 UTC, kommunist commented on internal/app/filestorage/access.go
> +	return nil, nil
Не стал делать, боюсь, что не уложусь в сроки(

2024-09-04 08:49 UTC, kommunist commented on internal/app/mapstorage/storage.go
> +func (db *Storage) GetByUserID(ctx context.Context, userID string) (map[string]string, error) {
Не стал делать, боюсь, что не уложусь в сроки(

2024-09-06 02:17 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью четвёртого спринта! 🎉 Желаю удачи на выпускном проекте 🍀

2024-09-06 02:17 UTC, vokinneberg commented on internal/app/pgstorage/access.go
> +	trn, err := d.driver.Begin()
Я бы рекомендовал именовать транзакцию `tx`, если нет противоречий, так как глаз уже автоматом ищет ее; так же не стоит забывать про `Rollback(...)`.

2024-09-06 07:26 UTC, merged