Iter20
kommunist/mishin-shortener pull request #25
Opened 2024-11-03 11:41 UTC by kommunist

2024-11-10 00:01 UTC, vokinneberg requested changes
Поздравляю с первым ревью седьмого спринта! 🎉 Ты сделал улучшения своего приложения 👍 Тем не менее, по традиции хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Ты реализовал статический анализатор 👍
2. Ты добавил новые флаги в приложение. 🙌
3. Ты улучшил покрытие приложения тестами. ⚡

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Можно добавить свой статический анализатор в GitHub workflow для того, чтобы проверки выполнялись при сборке.
- Ты не добавил все анализаторы в свой multichecker, которые требуются по условию задачи.

2024-11-10 00:01 UTC, vokinneberg commented on cmd/staticlint/multichecker.go
> +	for _, v := range staticcheck.Analyzers {
По  условию задачи :
_Создайте свой multichecker, состоящий из:
стандартных статических анализаторов пакета golang.org/x/tools/go/analysis/passes;
всех анализаторов класса SA пакета staticcheck.io;
не менее одного анализатора остальных классов пакета staticcheck.io;
двух или более любых публичных анализаторов на ваш выбор._
Мне кажется ты не выполнил пункты 1, 4.

2024-11-10 00:01 UTC, vokinneberg commented on internal/api/api.go
> +		os.Exit(1)
Не стоит вызывать `os.Exit()` из компонента, я советую вернуть ошибку и обработать ее в `main`. Если это запрещено статическим анализатором, можно вызвать `panic()`.

2024-11-10 12:29 UTC, kommunist commented on internal/api/api.go
> +		os.Exit(1)
Переделал

2024-11-10 12:30 UTC, kommunist commented on cmd/staticlint/multichecker.go
> +	for _, v := range staticcheck.Analyzers {
Добавил нужные проверки и сделал линтер в гитхаб-акшонс

2024-11-12 03:15 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью восьмого спринта! 🎉 Спасибо за подробное описание PR. 🙏

2024-11-12 07:40 UTC, merged