Iter23
kommunist/mishin-shortener pull request #29
Opened 2024-11-17 12:21 UTC by kommunist

2024-11-22 01:45 UTC, vokinneberg requested changes
Поздравляю с первым ревью девятого спринта! 🎉 Продолжаем улучшать наше приложение и покрывать его тестами! ⚡ По традиции хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Спасибо, что добавил подробное описание PR. 👍
2. Улучшил структуру своего приложения. 🚀
3. Ты реализовал функционал, требующийся по ТЗ 👍
4. Ты улучшил покрытие кода тестами 🙌

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Все-таки я бы советовал возвращать ошибку из `head` и обрабатывать ее в методе `main` - это было бы нагляднее.
2. Не все тесты к сожалению выполнятся. Получаю ошибку при запуске `go test ./... -coverprofile cover && go tool cover -func cover`:
    
    ```
    --- FAIL: TestCreateURLByJSONBatch (0.00s)
        --- FAIL: TestCreateURLByJSONBatch/Start_POST_to_create_record_in_storage (0.00s)
            create_url_by_json_batch_test.go:57: 
                	Error Trace:	/Users/a206700522/sources/yandex-praktukum/IvanMishin/mishin-shortener/internal/app/handlers/create_url_by_json_batch_test.go:57
                	Error:      	Not equal: 
                	           	expected: "http://localhost:8080/931691969b142b3a0f11a03e36fcc3b7"
                	           	actual  : "http://localhost:8000/931691969b142b3a0f11a03e36fcc3b7"
                	           	
                	           	Diff:
                	           	--- Expected
                	           	+++ Actual
                	           	@@ -1 +1 @@
                	           	-http://localhost:8080/931691969b142b3a0f11a03e36fcc3b7
                	           	+http://localhost:8000/931691969b142b3a0f11a03e36fcc3b7
                	Test:       	TestCreateURLByJSONBatch/Start_POST_to_create_record_in_storage
            create_url_by_json_batch_test.go:59: 
                	Error Trace:	/Users/a206700522/sources/yandex-praktukum/IvanMishin/mishin-shortener/internal/app/handlers/create_url_by_json_batch_test.go:59
                	Error:      	Not equal: 
                	           	expected: "http://localhost:8080/2cce0ec300cfe8dd3024939db0448893"
                	           	actual  : "http://localhost:8000/2cce0ec300cfe8dd3024939db0448893"
                	           	
                	           	Diff:
                	           	--- Expected
                	           	+++ Actual
                	           	@@ -1 +1 @@
                	           	-http://localhost:8080/2cce0ec300cfe8dd3024939db0448893
                	           	+http://localhost:8000/2cce0ec300cfe8dd3024939db0448893
                	Test:       	TestCreateURLByJSONBatch/Start_POST_to_create_record_in_storage
    2024/11/21 20:28:32 ERROR Parsing Error err="invalid character 'a' looking for beginning of value"
    2024/11/21 20:28:32 ERROR push to storage error err=another_error
    --- FAIL: TestPingHandler (0.00s)
        --- FAIL: TestPingHandler/when_not_pg_storage_then_error (0.00s)
            ping_test.go:26: 
                	Error Trace:	/Users/a206700522/sources/yandex-praktukum/IvanMishin/mishin-shortener/internal/app/handlers/ping_test.go:26
                	Error:      	Not equal: 
                	           	expected: 500
                	           	actual  : 200
                	Test:       	TestPingHandler/when_not_pg_storage_then_error
    FAIL
    coverage: 73.6% of statements
    FAIL	mishin-shortener/internal/app/handlers	4.255s
    ok  	mishin-shortener/internal/app/hasher	4.727s	coverage: 100.0% of statements
    ok  	mishin-shortener/internal/app/midleware	2.154s	coverage: 70.0% of statements
    ok  	mishin-shortener/internal/app/secure	2.214s	coverage: 73.2% of statements
    ok  	mishin-shortener/internal/handlers/deleteurls	1.649s	coverage: 75.0% of statements
    2024/11/21 20:28:33 INFO flags inited
    2024/11/21 20:28:33 ERROR push to storage error err=another
    --- FAIL: TestCall (0.00s)
        --- FAIL: TestCall/post_simple_create_happy_path (0.00s)
            simeplecreate_test.go:96: 
                	Error Trace:	/Users/a206700522/sources/yandex-praktukum/IvanMishin/mishin-shortener/internal/handlers/simplecreate/simeplecreate_test.go:96
                	Error:      	Not equal: 
                	           	expected: "http://localhost:8080/931691969b142b3a0f11a03e36fcc3b7"
                	           	actual  : "http://localhost:8000/931691969b142b3a0f11a03e36fcc3b7"
                	           	
                	           	Diff:
                	           	--- Expected
                	           	+++ Actual
                	           	@@ -1 +1 @@
                	           	-http://localhost:8080/931691969b142b3a0f11a03e36fcc3b7
                	           	+http://localhost:8000/931691969b142b3a0f11a03e36fcc3b7
                	Test:       	TestCall/post_simple_create_happy_path
        --- FAIL: TestCall/post_simple_create_when_record_exist_in_db (0.00s)
            simeplecreate_test.go:96: 
                	Error Trace:	/Users/a206700522/sources/yandex-praktukum/IvanMishin/mishin-shortener/internal/handlers/simplecreate/simeplecreate_test.go:96
                	Error:      	Not equal: 
                	           	expected: "http://localhost:8080/931691969b142b3a0f11a03e36fcc3b7"
                	           	actual  : "http://localhost:8000/931691969b142b3a0f11a03e36fcc3b7"
                	           	
                	           	Diff:
                	           	--- Expected
                	           	+++ Actual
                	           	@@ -1 +1 @@
                	           	-http://localhost:8080/931691969b142b3a0f11a03e36fcc3b7
                	           	+http://localhost:8000/931691969b142b3a0f11a03e36fcc3b7
                	Test:       	TestCall/post_simple_create_when_record_exist_in_db
    FAIL
    coverage: 84.2% of statements
    FAIL	mishin-shortener/internal/handlers/simplecreate	4.689s
    2024/11/21 20:28:31 INFO flags inited
    --- FAIL: TestCall (0.00s)
        --- FAIL: TestCall/post_to_create_record_in_db (0.00s)
            userurls_test.go:110: 
                	Error Trace:	/Users/a206700522/sources/yandex-praktukum/IvanMishin/mishin-shortener/internal/handlers/userurls/userurls_test.go:110
                	Error:      	[]userurls.responseItem{userurls.responseItem{Short:"http://localhost:8000/short0", Original:"long0"}, userurls.responseItem{Short:"http://localhost:8000/short1", Original:"long1"}} does not contain userurls.responseItem{Short:"http://localhost:8080/short0", Original:"long0"}
                	Test:       	TestCall/post_to_create_record_in_db
                	Messages:   	response contain correct result
            userurls_test.go:110: 
                	Error Trace:	/Users/a206700522/sources/yandex-praktukum/IvanMishin/mishin-shortener/internal/handlers/userurls/userurls_test.go:110
                	Error:      	[]userurls.responseItem{userurls.responseItem{Short:"http://localhost:8000/short0", Original:"long0"}, userurls.responseItem{Short:"http://localhost:8000/short1", Original:"long1"}} does not contain userurls.responseItem{Short:"http://localhost:8080/short1", Original:"long1"}
                	Test:       	TestCall/post_to_create_record_in_db
                	Messages:   	response contain correct result
    FAIL
    ```

2024-11-22 01:45 UTC, vokinneberg commented on cmd/shortener/main.go
> +	// go func() { // сервер для профилирования
Не стоит оставлять закомментированный код, я бы рекомендовал добавить флаг конфигурации, который включал бы профилирование.

2024-11-22 01:45 UTC, vokinneberg commented on internal/head/head.go
> +		panic(err)
 Все-таки я бы советовал возвращать ошибку и обрабатывать ее в методе `main` - это было бы нагляднее.

2024-11-22 01:45 UTC, vokinneberg commented on internal/api/router.go
> +	delasync.InitWorker(a.delChan, h.DB.DeleteByUserID) // не дело из api запускать асинхрон. Но пока так
 Согласен, не совсем очевидно и нарушает single responsibility principle. Стоит перенести на другой уровень.

2024-11-22 01:45 UTC, vokinneberg commented on internal/head/head_test.go
> +	t.Run("happy path on start full", func(t *testing.T) {
Не стоит использовать пробелы в названии тестов, так как Go заменяет из на `_`  автоматически и становился сложно искать тест по имени. Стоит либо сразу заменять ` ` на `_`, либо не использовать пробелы.

2024-11-23 09:39 UTC, kommunist commented on cmd/shortener/main.go
> +	// go func() { // сервер для профилирования
Сделал конфигурацию на сервер для профилировщика. И утащил в app

2024-11-23 09:39 UTC, kommunist commented on internal/head/head.go
> +		panic(err)
Сделал

2024-11-23 09:40 UTC, kommunist commented on internal/api/router.go
> +	delasync.InitWorker(a.delChan, h.DB.DeleteByUserID) // не дело из api запускать асинхрон. Но пока так
Переделал этот момент.
Теперь цепочка такая
main-> app -> api
                     -> delasync
                     
Выключение так же по слоям сделал

2024-11-23 09:40 UTC, kommunist commented on internal/head/head_test.go
> +	t.Run("happy path on start full", func(t *testing.T) {
Исправил

2024-11-23 09:48 UTC, kommunist commented
Евгений, после вытаскивания асинхрона из API не смог остановиться и зарефакторил оставшуюся часть хендлеров. Поэтому может казаться, что получилось много. Но теперь структурой проекта я "почти доволен")))

1) Поправил комментарии, которые ты оставил.
2) Закончил рефакторинг хендеров. Привел их всех к единой структуре. Это позволило избавиться от единого пакет handlers, который уже стал не удобен на текущий момент.
3) Так же избавился от одного большого интерфейса на базу. Теперь для каждого слоя интерфейс собирается как композиция из интерфейсов, лежащих уровнем ниже.
4) Из app закончил вытаскивать все и соответственно head(который был на прошлом этапе ревью) законно превратился в пакет app, как я и задумывал в начале рефактиринга.
5) Запуск асинхрона теперь происходит не из api, а из пакета app, как и должно быть. 
6) Для всех хендлеров, которые порефачил все переделал на бренчтесты.

Что касается тестов: в прошлый раз они не могли падать и не падают сейчас же, так как я сдавал со всеми зелеными галочками на WorkflowActions, а во 2ом инкременте проверяются тесты.

С покрытием так же все в порядке.
![image](https://github.com/user-attachments/assets/11cb846f-8f50-4f25-892d-7accca42edfa)

2024-11-26 00:26 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью девятого спринта! 🎉 Ты значительно улучшил структуру тестов и у твоего приложения отличный процент покрытия. Так держать! 🙌

2024-11-27 07:40 UTC, merged