[Iter5] Finish iter
kommunist/mishin-shortener pull request #5
Opened 2024-07-06 13:36 UTC by kommunist

2024-07-11 20:54 UTC, vokinneberg requested changes
Поздравляю с завершением Первого Спринта и первым ревью! 🤗 Твой код хорошо структурирован, покрыт тестами, работает и проходит тесты. Отличная работа! 🚀

**Сильные стороны твоего PR:**

1. **Функциональность**: Код функционален и корректен!
2. **Тестирование.** Реализованы тесты базовых сценариев.
3. **Структура сервиса.** По условию задания структура сервиса должна представлять собой набор пакетов и структур, разделённых на слои. Код неплохо структурирован и разбит на отдельные компоненты и пакеты.

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. **Реализация интерфейсов.** Слой `storage` должен имплементировать интерфейс хранения, например `repositories`. Это понадобится вам для подмены хранилища моком в тестах и использования DI.
2. **Синхронизация доступа** к хранилищу в агенте и на сервере. Стоит подумать, как будет себя вести код при конкурентной обработке нескольких запросов на сервере и как можно синхронизировать доступ к хранилищу.
3. **Обработка ошибок.** Не стоит злоупотреблять вызовом `panic(…)`, особенно в хендлерах, так как это приведет к краху приложения.
4. **Тестирование.** Поработай над реализацией более информативных сообщений в тестах.
5. **Комментарии.** Было бы здорово, если бы ты добавил комментарии в коде там, где есть сложные места, которые требуют пояснения, а также для публичных методов.

Более детальные комментарии ты найдёшь в PR.

2024-07-11 20:54 UTC, vokinneberg commented on cmd/shortener/main.go
> +)
Было бы здорово отсортировать импорты. Автоматическую сортировку при сохранении можно включить в VSCode.

```suggestion
	"fmt"
	"net/http"

	"mishin-shortener/internal/app/config"
	"mishin-shortener/internal/app/handlers"
	"mishin-shortener/internal/app/storage"

	"github.com/go-chi/chi/v5"
)
```

2024-07-11 20:54 UTC, vokinneberg commented on cmd/shortener/main.go
> +		panic(err)
Хотя это валидная техника, не стоит использовать `panic(...)`, так как это приведет к краху приложения. Я рекомендую использовать `log.Fatalf("Server failed to start: %v", err)`.  Это позволит вывести сообщение об ошибке и завершить процесс при помощи  `os.Exit(1)`.

2024-07-11 20:54 UTC, vokinneberg commented on cmd/shortener/main.go
> +	fmt.Println("Server started on", config.Config.BaseServerURL)
Рекомендую использовать log для логирования вместо `fmt.Println(...)`.

```suggestion
	log.Printf("Server started on %s", config.Config.BaseServerURL)
```

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/config/config.go
> +func init() {
Не рекомендую использовать глобальные переменные и инициализацию на уровне пакета. Рассмотри возможность использовать фабричный метод для создания инстанса `MainConfig`.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/storage/storage.go
> +func (db *Database) Get(shortURL string) string {
Возможно стоит реализовать проверку наличия `shortURL` в хранилище и в случае, если значение нет возвращать ошибку? Эту ошибку можно будет обработать в хендлере.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/get_handler.go
> +func GetHandler(w http.ResponseWriter, r *http.Request, db *storage.Database) {
Вместо передачи `db *storage.Database` как параметра, я бы рекомендовал реализовать тип хендлера в виде структуры, в которой можно хранить указатель на инстанс стораджа и фабричный метод, с помощью которого создавать инстанс хендлера при инициализации приложения. Это также позволит использовать методы хендлера напрямую, не оборачивая их в дополнительную функцию.

Так же по условиям задачи  что слой `storage` должен имплементировать интерфейс хранения, например `repositories`. Это понадобится вам для подмены хранилища моком в тестах и использования DI.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/get_handler.go
> +func GetHandler(w http.ResponseWriter, r *http.Request, db *storage.Database) {
Можно было бы использовать более информативное имя для метода хендлера, например `ShortenURL`. Так же это позволит не изменять имя хендлера в случае, если у нас появится еще один GET эндпоинт.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/post_handler.go
> +func PostHandler(w http.ResponseWriter, r *http.Request, db *storage.Database, redirectHost string) {
Рекомендации относительно `PostHandler` так же работают для `PostHandler `. Стоит реализовать оба метода в одном и том же типе хендлера и использовать общий инстанс для обработки запросов.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/get_handler.go
> +		http.Error(w, "Bad Request", http.StatusBadRequest)
В случае, если URL не найден в хранилище более логично было бы возвращать `404 NotFound`, а не `BadRequest`.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/post_handler.go
> +	if r.RequestURI == "/" {
Мне кажется эта проверка лишняя, так как `chi` сам обработает и вернет 404 NotFound для не зарегистрированного URL.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/post_handler.go
> +			panic(err)
Не стоит использовать panic(...) в хендлере, так как это приведет к краху приложения. Я рекомендую обработать ошибку, залогировать ее и вернуть сообщение об ошибке.
```suggestion
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			return
```

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/post_handler.go
> +		body, err := io.ReadAll(r.Body)
Стоит закрыть r.Body, при завершении работы хендлера.
```suggestion
		body, err := io.ReadAll(r.Body)
		defer r.Body.Close()
```

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/post_handler.go
> +		db.Push("/"+hashed, string(body))
Проверь еще раз — нужен ли тут слеш? Возможно, лучше добавить слеш при формировании URL в GET хендлере?

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/config/config.go
> +	flag.Parse()
Я не настаиваю, но мне кажется более консистентным такое поведение, когда флаги командной строки переопределяют переменные окружения.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/post_handler.go
> +		hashed := hasher.GetMD5Hash(body)
Стоит ли предусмотреть обработку коллизии хеша?

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/get_handler_test.go
> +    t.Run("Start GET on not persisted url", func(t *testing.T) {
Попробуй реализовать те же самые проверки в виде табличных тестов.

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/get_handler_test.go
> +        assert.Equal(t, http.StatusBadRequest, res.StatusCode)
Хотя в этом нет ничего принципиально неправильного, Go разработчики не рекомендуют использовать сторонние assert библиотеки так как это либо останавливает тест раньше времени (если вызовы утверждения `t.Fatalf(...)` или `panic(...)`), либо опускает интересную информацию о том, что тест сделал правильно. Это также заставляет  assert библиотеку создавать совершенно новый подъязык вместо использования существующего языка программирования (самого Go).

2024-07-11 20:54 UTC, vokinneberg commented on internal/app/handlers/get_handler_test.go
> +    t.Run("Start GET on not persisted url", func(t *testing.T) {
Небольшая рекомендация по поводу именования тестов - так как Go автоматически заменяет пробелы на подчеркивания в названиях тестов, трудно и скать тесты по коду. Я бы рекомендовал либо не использовать пробелы в названиях тестов, либо сразу заменить их на подчеркивания.

2024-07-13 11:44 UTC, kommunist commented on cmd/shortener/main.go
> +)
Что за чудо этот VScode) Последние 10 лет использовал atom.
Настроил, исправлено

2024-07-13 11:45 UTC, kommunist commented on cmd/shortener/main.go
> +		panic(err)
Согласен, исправлено

2024-07-13 11:45 UTC, kommunist commented on cmd/shortener/main.go
> +	fmt.Println("Server started on", config.Config.BaseServerURL)
Согласен, log гораздо информативнее выглядит. Исправлено

2024-07-13 11:46 UTC, kommunist commented on internal/app/config/config.go
> +func init() {
Меня тоже смутило на самом деле использование глобальной переменной, когда писал. Но тогда ничего лучше не придумал. 

Исправлено

2024-07-13 11:46 UTC, kommunist commented on internal/app/storage/storage.go
> +func (db *Database) Get(shortURL string) string {
Добавил проверку, обработку и тест на это

2024-07-13 11:49 UTC, kommunist commented on internal/app/handlers/get_handler.go
> +func GetHandler(w http.ResponseWriter, r *http.Request, db *storage.Database) {
Что касается передачи указателя на базу переделал на структуру. Так действительно значительно удобнее. Переделал оба хендлера: и на редирект и не создание.

А вот на счет storage не понял. У меня в storage реализованы методы Get и Post, которые сейчас просто добавляют и вычитывают из мапы. В перспективе понимаю, что они изменятся на select и insert, когда притащим базу. Поэтому не понял здесь про слой хранения

2024-07-13 11:49 UTC, kommunist commented on internal/app/handlers/get_handler.go
> +func GetHandler(w http.ResponseWriter, r *http.Request, db *storage.Database) {
Переименовал хендлеры

2024-07-13 11:50 UTC, kommunist commented on internal/app/handlers/post_handler.go
> +func PostHandler(w http.ResponseWriter, r *http.Request, db *storage.Database, redirectHost string) {
Оба перенесены как методы структуры

2024-07-13 11:50 UTC, kommunist commented on internal/app/handlers/get_handler.go
> +		http.Error(w, "Bad Request", http.StatusBadRequest)
Добавлено

2024-07-13 11:50 UTC, kommunist commented on internal/app/handlers/post_handler.go
> +	if r.RequestURI == "/" {
Согласен, лишняя.
Убрал

2024-07-13 11:50 UTC, kommunist commented on internal/app/handlers/post_handler.go
> +			panic(err)
Согласен, убрал

2024-07-13 11:51 UTC, kommunist commented on internal/app/handlers/post_handler.go
> +		body, err := io.ReadAll(r.Body)
Добавил, но в теле курса видел, что можно не закрывать и что оно закрывается само.

2024-07-13 11:52 UTC, kommunist commented on internal/app/handlers/post_handler.go
> +		db.Push("/"+hashed, string(body))
Да, слеш тут оставил.
Потому что тогда удобно при доставании из базы: можно не пытаться вычленять из url именно часть без хеша. В общем, так действительно удобнее

2024-07-13 11:54 UTC, kommunist commented on internal/app/handlers/post_handler.go
> +		hashed := hasher.GetMD5Hash(body)
Думаю, что в перспективе стоило бы. Сейчас не стал заморачиваться. Будем счиать, что в случае коллизии кто последний пришел, того и тапки.

2024-07-13 11:57 UTC, kommunist commented on internal/app/handlers/get_handler_test.go
> +    t.Run("Start GET on not persisted url", func(t *testing.T) {
Реализовал, но только в Redirect, где два теста относительно похожих.
Честно сказать, подход с матрицей не очень понравился. В настоящем боевом проекте на работе часто приходится править только один тест. А это повлечет изменение схемы матрицы и может увеличить время  исправления.
Хотя, возможно стоит смотреть на это как на способ поддержания тестовой базы в чистоте

2024-07-13 11:58 UTC, kommunist commented on internal/app/handlers/get_handler_test.go
> +        assert.Equal(t, http.StatusBadRequest, res.StatusCode)
Почитал в рокете баталии и пока решил оставить использование как есть

2024-07-13 11:58 UTC, kommunist commented on internal/app/handlers/get_handler_test.go
> +    t.Run("Start GET on not persisted url", func(t *testing.T) {
Исправил везде названия тестов

2024-07-13 11:58 UTC, kommunist commented on internal/app/config/config.go
> +	flag.Parse()
Согласен, самому такое поведение больше кажется логичным, но по условиям задачи:

```
Приоритет параметров сервера должен быть таким:
Если указана переменная окружения, то используется она.
Если нет переменной окружения, но есть аргумент командной строки (флаг), то используется он.
Если нет ни переменной окружения, ни флага, то используется значение по умолчанию.
```

2024-07-17 22:21 UTC, vokinneberg commented on cmd/shortener/main.go
> +		os.Exit(1)
`os.Exit(1)` можно убрать, так как `log.Fatal()` уже делает этот вызов.
```suggestion
		log.Fatalf("Server failed to start: %v", err)
```

2024-07-17 22:21 UTC, vokinneberg commented on internal/app/config/config.go
> +	flag.Parse()
Да, я об этом забыл. 👍

2024-07-17 22:21 UTC, vokinneberg commented on internal/app/handlers/get_handler.go
> +func GetHandler(w http.ResponseWriter, r *http.Request, db *storage.Database) {
Имелось ввиду использование интерфейса доступа к БД вместо конкретной реализации. Тебе это позволить "отвязаться" от конкретной реализации и в последствии будет проще заменить реализацию на реализацию с БД.

Например:

```go
type Storage interface {
    func Push(shortURL string, originalURL string)
    func Get(shortURL string) (string, error) 
}
```

Твой storage реализует этот интерфейс с следовательно его можно просто передать в хендлер.

2024-07-17 22:21 UTC, vokinneberg commented on internal/app/handlers/post_handler.go
> +		body, err := io.ReadAll(r.Body)
Действительно! Спасибо, что указал на это 🙏

2024-07-17 22:21 UTC, vokinneberg commented on internal/app/config/config.go
> +	flag.Parse()
 Так же забыл про это требование! Спасибо 🙏

2024-07-17 22:24 UTC, vokinneberg commented on internal/app/handlers/get_handler_test.go
> +    t.Run("Start GET on not persisted url", func(t *testing.T) {
В моей практике табличные тесты превалируют так как как правило возникает необходимость протестировать одну и ту же логику на различные кейсы.

2024-07-17 22:26 UTC, vokinneberg approved these changes
Здорово! 👍 Я оставил пару дополнительных комментариев, над которыми мы сможем поработать в следующем спринте. Спасибо за то, что указал мне на мои неточности 🙏 Поздравляю с завершением первого спринта и завершением первого ревью! 🤗 Отличная работа! 🚀

2024-07-18 04:57 UTC, merged